[project]
name = "wsbm-comparison"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.9",
    "netgraph>=4.13.2",
    "networkx>=3.4.2",
    "numpy>=2.2.6",
    "reservoirpy",
    "scikit-learn>=1.7.2",
]

[tool.hatch.build.targets.wheel]
packages = ["src"]

[tool.uv.sources]
reservoirpy = { git = "https://github.com/sabertoaster/reservoirpy.git", rev = "wsbm-fix" }
